// <auto-generated />
namespace Reflector.DataAccess.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMethods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMethods));
        
        string IMigrationMetadata.Id
        {
            get { return "201801052245496_AddMethods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
